# NumPy

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

In [72]:
import numpy as np
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

#### ndarray.ndim

The number of axes (dimensions) of the array.

In [9]:
a.ndim

2

#### ndarray.shape

The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`.

In [11]:
a.shape

(4, 4)

#### ndarray.size

The total number of elements of the array. This is equal to the product of the elements of `shape`.

In [12]:
a.size

16

#### ndarray.dtype

An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [18]:
a.dtype

dtype('int64')

#### ndarray.itemsize

The size in bytes of each element of the array. For example, an array of elements of type `float64` has `itemsize` 8 (=64/8), while one of type `complex32` has `itemsize` 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`.

In [19]:
a.itemsize

8

#### ndarray.data

The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [20]:
a.data

## References
* Types: https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases
* Functions: https://numpy.org/doc/stable/reference/routines.html

## Logic Functions

In [99]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [100]:
np.all(x)

False

In [101]:
np.any(x)

True

In [102]:
np.logical_and(x, y)

array([ True, False, False, False])

In [103]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [104]:
np.logical_xor(x, y)

array([False,  True,  True, False])

In [105]:
np.logical_not(x)

array([False, False,  True,  True])

## Comparison

In [106]:
np.array_equal(x, y)

False

In [107]:
np.array_equiv(x, y)

False

In [108]:
np.empty(shape=(5, 5), dtype=np.int8)

array([[   0,    0,    0,    0,    0],
       [   0,    0, -128,   79,   28],
       [ -38,  -34,   -2,    7,    0],
       [  64,    2,    0,    0,    0],
       [   0,    0,    0,    0,    0]], dtype=int8)

## Others

In [109]:
np.ones(shape=(5, 5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [110]:
np.zeros(shape=(5, 5), dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [111]:
np.arange(20).reshape(10, 2).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [112]:
np.resize(np.arange(20), (2, 2))

array([[0, 1],
       [2, 3]])