# Tensor Flow

In [1]:
import tensorflow as tf
import numpy as np

2023-02-11 08:23:27.069192: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Constant Tensors

In [2]:
tf.constant(3)

2023-02-11 08:23:53.771689: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
tf.constant([[1, 2, 3], [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
x1 = tf.constant([1, 2, 3])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2])
tf.stack([x3, x3, x3])

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

### Slicing

In [6]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
tf.shape(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [10]:
x[:, 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

### Reshape

In [11]:
tf.reshape(x, (3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Variable Tensors

The shape and type of the variable tensor it's constant and doesn't change once defined. What is variable, are the values in it.

In [12]:
var = tf.Variable(2)
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [13]:
var.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=5>

In [14]:
var.assign_add(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>

In [15]:
var.assign_sub(1)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=6>

## Matrix multiplication

In [16]:
# w * x

In [17]:
w = tf.Variable([[1], [2]], dtype=np.float32)
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [18]:
x = tf.constant([[3, 4]], dtype=np.float32)
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3., 4.]], dtype=float32)>

In [19]:
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>