# Tensor Flow

In [46]:
import tensorflow as tf
import numpy as np

## Constant Tensors

In [47]:
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [7]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [11]:
tf.constant([[1, 2, 3], [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
x1 = tf.constant([1, 2, 3])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2])
tf.stack([x3, x3, x3])

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

### Slicing

In [26]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [24]:
tf.shape(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [43]:
x[:, 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

### Reshape

In [44]:
tf.reshape(x, (3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Variable Tensors

The shape and type of the variable tensor it's constant and doesn't change once defined. What is variable, are the values in it.

In [52]:
var = tf.Variable(2)
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [53]:
var.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=5>

In [54]:
var.assign_add(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=7>

In [55]:
var.assign_sub(1)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=6>

## Matrix multiplication

In [58]:
# w * x

In [64]:
w = tf.Variable([[1], [2]], dtype=np.float32)
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [69]:
x = tf.constant([[3, 4]], dtype=np.float32)
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3., 4.]], dtype=float32)>

In [72]:
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

## Calculate loss gradient