# Examples

## Import numpy as np and see the version

In [3]:
import numpy as np
np.__version__

'1.24.1'

## How to create a 1D array

Create a 1D array of numbers from 0 to 9

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## How to create a boolean array

Create a 3×3 numpy array of all True’s

In [7]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## How to extract items that satisfy a given condition from 1D array

Extract all odd numbers from `array`

In [93]:
array = np.arange(10, 21)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
array[array % 2 != 0]

array([11, 13, 15, 17, 19])

## How to replace items that satisfy a condition with another value in numpy array

Replace all odd numbers in `array` with -1

In [29]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
array[array % 2 != 0] = -1
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

## How to replace items that satisfy a condition without affecting the original array

Replace all odd numbers in `array` with -1 without changing the original array

In [36]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
copy_array = array.copy()
copy_array[copy_array % 2 != 0] = -1

In [38]:
copy_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [39]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

or you can also use `where`

In [45]:
array = np.arange(11)
np.where(array % 2 != 0, -1, array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [46]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## How to reshape an array

In [56]:
np.arange(51).reshape(3, -1) # the -1 automatically decides how many columns left

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50]])

## How to generate automatic custom sequences

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Desired input

```
a = np.array([1,2,3])
```

Desired output

```
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [57]:
a = np.array([1,2,3])

We can use `repeat` and `tile` to generate the two patterns

In [72]:
p1 = np.repeat(a, 3)
p1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [73]:
p2 = np.tile(a, 3)
p2

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

and then we can concatenate the results together with various methods

In [75]:
np.concatenate((p1, p2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [77]:
np.hstack((p1, p2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## How to get the common items between two python numpy arrays

Get the common items between a and b

In [79]:
a = [1, 3, 7, 11, 22]
b = [22, 7, 13]

In [80]:
np.intersect1d(a, b)

array([ 7, 22])

## How to remove from one array those items that exist in another

From array `a` remove all items present in array `b`

In [84]:
a = np.array([1,2,3,4,5])
b = np.array([4, 5,6,7,8])

In [85]:
np.setdiff1d(a, b)

array([1, 2, 3])

In [86]:
np.setdiff1d(b, a)

array([6, 7, 8])

## How to get the indexes of matching elements

In [88]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [95]:
np.where(a == b)

(array([1, 3, 5, 7]),)

## How to extract all numbers between a given range from a numpy array

Get all items between 5 and 10 from a.

In [96]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

**Method 1**

In [100]:
a[np.where((a >= 5) & (a <= 10))]

array([ 6,  9, 10])

**Method 2**

In [101]:
a[np.where(np.logical_and(a >= 5, a <= 10))]

array([ 6,  9, 10])

**Method 3**

In [103]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## How to make a python function that handles scalars to work on numpy arrays

Convert the following function that works on two scalars, to work on two arrays.

```python
def vector_max(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```

In [105]:
def vector_max(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [106]:
vector_max(1, 5)

5

In [118]:
np.vectorize(vector_max)([1, 0, -1], [3, 5, -3])

array([ 3,  5, -1])

## How to compute the mean, median, standard deviation of a numpy array

Find the mean, median, variance and standard deviation of the following array.

In [150]:
a = np.random.randint(low=1, high=1000, size=50)
a

array([225, 104, 887, 113, 548, 938, 787, 703, 738, 482, 352, 151, 516,
        30, 539, 727, 519, 580, 707, 809, 157, 155, 694, 563,  74, 340,
       291, 156, 432, 265,  38, 653, 585, 941,  88, 638, 410, 404, 974,
       163, 210, 550, 274, 457, 990, 461, 723, 508, 258, 754])

In [151]:
np.median(a)

495.0

In [152]:
np.mean(a)

473.22

In [153]:
a.mean()

473.22

In [154]:
np.std(a)

271.2181623711804

In [155]:
a.std()

271.2181623711804

In [156]:
np.var(a)

73559.2916

In [157]:
a.var()

73559.2916

## How to find the percentile scores of a numpy array

Find the 5th and 95th percentile of the following distribution

In [168]:
a = np.random.randint(low=0, high=10000, size=1000)

In [169]:
np.percentile(a, q=[5, 95])

array([ 419.85, 9436.3 ])