# Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


## Addition

### Array by Array

In [3]:
a1 = np.array([2, 3, 4, 5])
b1 = np.array([-1, 10, -23, 7])

In [4]:
a1 + b1

array([  1,  13, -19,  12])

In [5]:
b1 + a1

array([  1,  13, -19,  12])

### Array by Scalar

In [6]:
np.array([2, 2, 2, 2]) + 3

array([5, 5, 5, 5])

In [7]:
3 + np.array([2, 2, 2, 2])

array([5, 5, 5, 5])

In [8]:
- np.array([2, 2, 2, 2])

array([-2, -2, -2, -2])

## Multiplication

### Array by Array

In [9]:
a2 = np.array([2, 3, 4, 5])
b2 = np.array([-1, 10, -23, 7])

In [10]:
a2 * b2

array([ -2,  30, -92,  35])

In [11]:
b2 * a2

array([ -2,  30, -92,  35])

### Array by Scalar

In [12]:
np.array([2, 2, 2, 2]) * 3

array([6, 6, 6, 6])

In [13]:
3 * np.array([2, 2, 2, 2])

array([6, 6, 6, 6])

### Matrix by Matrix

In [14]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m2 = np.array([2,3,4])

In [15]:
m1 * m2

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [16]:
m1 @ m2

array([20, 47, 74])

In [17]:
np.matmul(m1, m2)

array([20, 47, 74])

## Matrix generation

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full((2, 3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.full((3, 3), 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.tile([1, 2, 3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
np.random.seed(42) # setting the seed
np.random.randint(0, 10, size = (3,3))

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [24]:
np.random.seed(42) # setting the seed
np.random.normal(size = (3,3))

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

## Matrix Transpose

In [25]:
matrix = np.random.randint(0, 100, size = (3,3))
matrix

array([[63, 59, 20],
       [32, 75, 57],
       [21, 88, 48]])

In [26]:
matrix.T

array([[63, 32, 21],
       [59, 75, 88],
       [20, 57, 48]])

## Range and linear space

In [27]:
np.linspace(0, 100, 5) # Generate 5 evenly spaced numbers between 0 and 100

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [31]:
np.arange(start=2, stop=11, step=2)

array([ 2,  4,  6,  8, 10])

## Reshape

In [32]:
twenty_seven = np.arange(36)
twenty_seven.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## Horizontal and Vertical stacking

In [33]:
np.hstack((np.array([ [7,8,9], [10,11,12] ]), np.array([ [1,2,3], [4,5,6] ])))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [34]:
np.hstack((np.array((1,2,3)), np.array((4,5,6))))

array([1, 2, 3, 4, 5, 6])

In [35]:
np.vstack((np.array([ [7,8,9], [10,11,12] ]), np.array([ [1,2,3], [4,5,6] ])))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [36]:
np.vstack((np.array((1,2,3)), np.array((4,5,6))))

array([[1, 2, 3],
       [4, 5, 6]])

## Where

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

np.where(a == b)

(array([0, 3, 4]),)

In [38]:
np.where(a > b)

(array([2]),)

In [39]:
np.where(a < b)

(array([1]),)