# Exercises

In [1]:
import numpy as np
a = np.arange(72).reshape((8, -1))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

What is the average value of the second column (to two decimal places)?

In [2]:
a[:, 1]

array([ 1, 10, 19, 28, 37, 46, 55, 64])

In [3]:
a[:, 1].mean()

np.float64(32.5)

What is the average value of the first 5 rows of the third and fourth columns?

In [4]:
a[0:5, (2, 3)]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39]])

In [5]:
a[0:5, (2, 3)].mean()

np.float64(20.5)